//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFlearning.IDE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFlearning.IDE.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?utm_source=kflearning_desktop&amp;utm_medium=.
        /// </summary>
        public static string AnalyticsCampaignQuery {
            get {
                return ResourceManager.GetString("AnalyticsCampaignQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string CampaignAbout {
            get {
                return ResourceManager.GetString("CampaignAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navbar.
        /// </summary>
        public static string CampaignNav {
            get {
                return ResourceManager.GetString("CampaignNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reader.
        /// </summary>
        public static string CampaignReader {
            get {
                return ResourceManager.GetString("CampaignReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KFlearning ZIP archive (*.zip)|*.zip.
        /// </summary>
        public static string FilterZip {
            get {
                return ResourceManager.GetString("FilterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zip.
        /// </summary>
        public static string FilterZipExtension {
            get {
                return ResourceManager.GetString("FilterZipExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Kodesiana/KFlearning.
        /// </summary>
        public static string GitHubUrl {
            get {
                return ResourceManager.GetString("GitHubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berkas ZIP yang Anda pilih tidak sesuai dengan format impor!.
        /// </summary>
        public static string ImportIncompatibleMessage {
            get {
                return ResourceManager.GetString("ImportIncompatibleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/fahminoorfiqri.
        /// </summary>
        public static string InstagramUrl {
            get {
                return ResourceManager.GetString("InstagramUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kodesiana.com.
        /// </summary>
        public static string WebUrl {
            get {
                return ResourceManager.GetString("WebUrl", resourceCulture);
            }
        }
    }
}
