//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFlearning.IDE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFlearning.IDE.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perbarui.
        /// </summary>
        public static string ActionArticleRefresh {
            get {
                return ResourceManager.GetString("ActionArticleRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari....
        /// </summary>
        public static string ActionArticleSearch {
            get {
                return ResourceManager.GetString("ActionArticleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batal.
        /// </summary>
        public static string ActionCancel {
            get {
                return ResourceManager.GetString("ActionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buat Proyek.
        /// </summary>
        public static string ActionCreateProject {
            get {
                return ResourceManager.GetString("ActionCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hapus.
        /// </summary>
        public static string ActionDelete {
            get {
                return ResourceManager.GetString("ActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspor.
        /// </summary>
        public static string ActionExport {
            get {
                return ResourceManager.GetString("ActionExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impor.
        /// </summary>
        public static string ActionImport {
            get {
                return ResourceManager.GetString("ActionImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string ActionOpenGithub {
            get {
                return ResourceManager.GetString("ActionOpenGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buka di Browser.
        /// </summary>
        public static string ActionOpenInBrowser {
            get {
                return ResourceManager.GetString("ActionOpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string ActionOpenInstagram {
            get {
                return ResourceManager.GetString("ActionOpenInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buka Workspace.
        /// </summary>
        public static string ActionOpenRepos {
            get {
                return ResourceManager.GetString("ActionOpenRepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buka Source Code.
        /// </summary>
        public static string ActionOpenSource {
            get {
                return ResourceManager.GetString("ActionOpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string ActionOpenTwitter {
            get {
                return ResourceManager.GetString("ActionOpenTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodesiana.com.
        /// </summary>
        public static string ActionOpenWeb {
            get {
                return ResourceManager.GetString("ActionOpenWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP Info.
        /// </summary>
        public static string ActionPhpInfo {
            get {
                return ResourceManager.GetString("ActionPhpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phpMyAdmin.
        /// </summary>
        public static string ActionPhpmyadmin {
            get {
                return ResourceManager.GetString("ActionPhpmyadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge.
        /// </summary>
        public static string ActionPurge {
            get {
                return ResourceManager.GetString("ActionPurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpan Offline.
        /// </summary>
        public static string ActionSaveOffline {
            get {
                return ResourceManager.GetString("ActionSaveOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buka Server.
        /// </summary>
        public static string ActionStartServer {
            get {
                return ResourceManager.GetString("ActionStartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutup Server.
        /// </summary>
        public static string ActionStopServer {
            get {
                return ResourceManager.GetString("ActionStopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias sudah ada untuk project ini..
        /// </summary>
        public static string AliasAlreadyExists {
            get {
                return ResourceManager.GetString("AliasAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membuat virtual host dan alias....
        /// </summary>
        public static string AliasCreatingMessage {
            get {
                return ResourceManager.GetString("AliasCreatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak ada alias untuk project ini..
        /// </summary>
        public static string AliasNotExists {
            get {
                return ResourceManager.GetString("AliasNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menghapus virtual host dan alias....
        /// </summary>
        public static string AliasRemovingMessage {
            get {
                return ResourceManager.GetString("AliasRemovingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-learning terpadu by Kodesiana.com.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KFlearning.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hak Cipta (C) Fahmi Noor Fiqri, Kodesiana.com 2019.
        /// </summary>
        public static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak dapat membuat proyek baru karena proyek dengan nama yang sama sudah ada..
        /// </summary>
        public static string CreateProjectDuplicateMessage {
            get {
                return ResourceManager.GetString("CreateProjectDuplicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membuat proyek....
        /// </summary>
        public static string CreateProjectMessage {
            get {
                return ResourceManager.GetString("CreateProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri.
        /// </summary>
        public static string CueArticleSeries {
            get {
                return ResourceManager.GetString("CueArticleSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode daring.
        /// </summary>
        public static string CueOfflineMode {
            get {
                return ResourceManager.GetString("CueOfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode luring.
        /// </summary>
        public static string CueOnlineMode {
            get {
                return ResourceManager.GetString("CueOnlineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama proyek.
        /// </summary>
        public static string CueProjectName {
            get {
                return ResourceManager.GetString("CueProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokasi proyek.
        /// </summary>
        public static string CueProjectPath {
            get {
                return ResourceManager.GetString("CueProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenis proyek.
        /// </summary>
        public static string CueProjectType {
            get {
                return ResourceManager.GetString("CueProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menghapus proyek....
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilih lokasi file untuk di ekspor..
        /// </summary>
        public static string DialogExportTitle {
            get {
                return ResourceManager.GetString("DialogExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilih file untuk di impor..
        /// </summary>
        public static string DialogImportTitle {
            get {
                return ResourceManager.GetString("DialogImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mengekspor proyek....
        /// </summary>
        public static string ExportMessage {
            get {
                return ResourceManager.GetString("ExportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mengimpor proyek....
        /// </summary>
        public static string ImportMessage {
            get {
                return ResourceManager.GetString("ImportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menyiapkan proyek C++....
        /// </summary>
        public static string InitCppMessage {
            get {
                return ResourceManager.GetString("InitCppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KFlearning merupakan aplikasi sumber terbuka, dilisensikan di bawah lisensi permisif MIT..
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentang.
        /// </summary>
        public static string NavbarAbout {
            get {
                return ResourceManager.GetString("NavbarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string NavbarApps {
            get {
                return ResourceManager.GetString("NavbarApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel.
        /// </summary>
        public static string NavbarArticles {
            get {
                return ResourceManager.GetString("NavbarArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyek.
        /// </summary>
        public static string NavbarProject {
            get {
                return ResourceManager.GetString("NavbarProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project belum dipilih/tidak valid..
        /// </summary>
        public static string NoProjectMessage {
            get {
                return ResourceManager.GetString("NoProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak dapat membuat symbolic link. Jalankan program sebagai Administrator..
        /// </summary>
        public static string NotElevatedMessage {
            get {
                return ResourceManager.GetString("NotElevatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic Link.
        /// </summary>
        public static string NotElevatedTitle {
            get {
                return ResourceManager.GetString("NotElevatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C/C++ Project.
        /// </summary>
        public static string ProjectCppName {
            get {
                return ResourceManager.GetString("ProjectCppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Project.
        /// </summary>
        public static string ProjectPythonName {
            get {
                return ResourceManager.GetString("ProjectPythonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web PHP Project.
        /// </summary>
        public static string ProjectWebName {
            get {
                return ResourceManager.GetString("ProjectWebName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apakah Anda yakin ingin melakukan PURGE? Semua proyek akan di hapus..
        /// </summary>
        public static string PurgeConfirmMessage {
            get {
                return ResourceManager.GetString("PurgeConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menghapus semua proyek....
        /// </summary>
        public static string PurgeProcessMessage {
            get {
                return ResourceManager.GetString("PurgeProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log server:.
        /// </summary>
        public static string ServerLogText {
            get {
                return ResourceManager.GetString("ServerLogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Host Alias.
        /// </summary>
        public static string TitleAlias {
            get {
                return ResourceManager.GetString("TitleAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyek baru.
        /// </summary>
        public static string TitleCreateProject {
            get {
                return ResourceManager.GetString("TitleCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hapus proyek.
        /// </summary>
        public static string TitleDelete {
            get {
                return ResourceManager.GetString("TitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekspor proyek.
        /// </summary>
        public static string TitleExport {
            get {
                return ResourceManager.GetString("TitleExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impor proyek.
        /// </summary>
        public static string TitleImport {
            get {
                return ResourceManager.GetString("TitleImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project C++.
        /// </summary>
        public static string TitleInitCpp {
            get {
                return ResourceManager.GetString("TitleInitCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilih project.
        /// </summary>
        public static string TitleNoProject {
            get {
                return ResourceManager.GetString("TitleNoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasi Purge.
        /// </summary>
        public static string TitlePurge {
            get {
                return ResourceManager.GetString("TitlePurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web server..
        /// </summary>
        public static string ViewTitleApps {
            get {
                return ResourceManager.GetString("ViewTitleApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel..
        /// </summary>
        public static string ViewTitleArticles {
            get {
                return ResourceManager.GetString("ViewTitleArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyek Anda..
        /// </summary>
        public static string ViewTitleProjects {
            get {
                return ResourceManager.GetString("ViewTitleProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server siap..
        /// </summary>
        public static string WebServerStatusReady {
            get {
                return ResourceManager.GetString("WebServerStatusReady", resourceCulture);
            }
        }
    }
}
