//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFlearning.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFlearning.Core.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HtmlBodyEnd {
            get {
                return ResourceManager.GetString("HtmlBodyEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HtmlBodyStart {
            get {
                return ResourceManager.GetString("HtmlBodyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kf-project.json.
        /// </summary>
        internal static string MetadataFileName {
            get {
                return ResourceManager.GetString("MetadataFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;window.zoomLevel&quot;: 0,
        ///    &quot;vsicons.dontShowNewVersionMessage&quot;: true,
        ///
        ///    &quot;terminal.integrated.shell.windows&quot;: &quot;C:\\WINDOWS\\System32\\cmd.exe&quot;,
        ///    &quot;terminal.integrated.rendererType&quot;: &quot;canvas&quot;,
        ///
        ///    &quot;[json]&quot;: {
        ///        &quot;editor.defaultFormatter&quot;: &quot;HookyQR.beautify&quot;
        ///    },
        ///    &quot;[html]&quot;: {
        ///        &quot;editor.defaultFormatter&quot;: &quot;HookyQR.beautify&quot;
        ///    },
        ///
        ///    &quot;editor.renderWhitespace&quot;: &quot;all&quot;,
        ///    &quot;editor.renderControlCharacters&quot;: true,
        ///    &quot;editor.detectIndentation&quot;: false,
        ///    &quot;editor.tabS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VscodeConfig {
            get {
                return ResourceManager.GetString("VscodeConfig", resourceCulture);
            }
        }
    }
}
