//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFlearning.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFlearning.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEST MATCH.
        /// </summary>
        public static string GachaAcquired {
            get {
                return ResourceManager.GetString("GachaAcquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU LOSE.
        /// </summary>
        public static string GachaFailed {
            get {
                return ResourceManager.GetString("GachaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMIC.
        /// </summary>
        public static string GachaItemComic {
            get {
                return ResourceManager.GetString("GachaItemComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIAMOND.
        /// </summary>
        public static string GachaItemDiamond {
            get {
                return ResourceManager.GetString("GachaItemDiamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GATLING.
        /// </summary>
        public static string GachaItemGatling {
            get {
                return ResourceManager.GetString("GachaItemGatling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GORILLA.
        /// </summary>
        public static string GachaItemGorilla {
            get {
                return ResourceManager.GetString("GachaItemGorilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NINJA.
        /// </summary>
        public static string GachaItemNinja {
            get {
                return ResourceManager.GetString("GachaItemNinja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RABBIT.
        /// </summary>
        public static string GachaItemRabbit {
            get {
                return ResourceManager.GetString("GachaItemRabbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAKA.
        /// </summary>
        public static string GachaItemTaka {
            get {
                return ResourceManager.GetString("GachaItemTaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TANK.
        /// </summary>
        public static string GachaItemTank {
            get {
                return ResourceManager.GetString("GachaItemTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sang programmer!.
        /// </summary>
        public static string QuestCoderComplete {
            get {
                return ResourceManager.GetString("QuestCoderComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulis 500 baris kode untuk mencapai Coder 1..
        /// </summary>
        public static string QuestCoderLevel1 {
            get {
                return ResourceManager.GetString("QuestCoderLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulis 1000 baris kode untuk mencapai Coder 1..
        /// </summary>
        public static string QuestCoderLevel2 {
            get {
                return ResourceManager.GetString("QuestCoderLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulis 1500 baris kode untuk mencapai Coder 1..
        /// </summary>
        public static string QuestCoderLevel3 {
            get {
                return ResourceManager.GetString("QuestCoderLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manusia fokus!.
        /// </summary>
        public static string QuestFocusComplete {
            get {
                return ResourceManager.GetString("QuestFocusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunakan VSCode selama 2 jam untuk mencapai Focus 1..
        /// </summary>
        public static string QuestFocusLevel1 {
            get {
                return ResourceManager.GetString("QuestFocusLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunakan VSCode selama 4 jam untuk mencapai Focus 1..
        /// </summary>
        public static string QuestFocusLevel2 {
            get {
                return ResourceManager.GetString("QuestFocusLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunakan VSCode selama 6 jam untuk mencapai Focus 1..
        /// </summary>
        public static string QuestFocusLevel3 {
            get {
                return ResourceManager.GetString("QuestFocusLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sang manajer!.
        /// </summary>
        public static string QuestProjectComplete {
            get {
                return ResourceManager.GetString("QuestProjectComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buat 5 project untuk mencapai Projects 1..
        /// </summary>
        public static string QuestProjectLevel1 {
            get {
                return ResourceManager.GetString("QuestProjectLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buat 10 project untuk mencapai Projects 1..
        /// </summary>
        public static string QuestProjectLevel2 {
            get {
                return ResourceManager.GetString("QuestProjectLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buat 15 project untuk mencapai Projects 1..
        /// </summary>
        public static string QuestProjectLevel3 {
            get {
                return ResourceManager.GetString("QuestProjectLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StarFilled {
            get {
                return ResourceManager.GetString("StarFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StarOutline {
            get {
                return ResourceManager.GetString("StarOutline", resourceCulture);
            }
        }
    }
}
