name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run Cake build
      run: PowerShell.exe -ExecutionPolicy Bypass -File ./build.ps1
